USE [master]
GO

/****** Object:  Database [DBMBCORP]    Script Date: 09/09/2014 12:15:17 ******/
CREATE DATABASE [DBMBCORP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBMBCORP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DBMBCORP.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBMBCORP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DBMBCORP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBMBCORP] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBMBCORP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBMBCORP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBMBCORP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBMBCORP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBMBCORP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBMBCORP] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBMBCORP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBMBCORP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DBMBCORP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBMBCORP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBMBCORP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBMBCORP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBMBCORP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBMBCORP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBMBCORP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBMBCORP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBMBCORP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBMBCORP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBMBCORP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBMBCORP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBMBCORP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBMBCORP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBMBCORP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBMBCORP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBMBCORP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBMBCORP] SET  MULTI_USER 
GO

ALTER DATABASE [DBMBCORP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBMBCORP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBMBCORP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBMBCORP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBMBCORP] SET  READ_WRITE 
GO



USE [DBMBCORP]
GO

/****** Object:  Table [dbo].[ACAO]    Script Date: 09/09/2014 12:11:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Empresa]    Script Date: 09/09/2014 12:12:04 ******/

GO

/****** Object:  Table [dbo].[Empresa]    Script Date: 09/09/2014 12:12:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Empresa](
	[CNPJ] [nvarchar](255) NOT NULL,
	[RAZAOSOCIAL] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[CNPJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[ACAO](
	[CODIGO] [nvarchar](255) NOT NULL,
	[CNPJ] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ACAO]  WITH CHECK ADD  CONSTRAINT [FKEA885BA44002CFEA] FOREIGN KEY([CNPJ])
REFERENCES [dbo].[Empresa] ([CNPJ])
GO

ALTER TABLE [dbo].[ACAO] CHECK CONSTRAINT [FKEA885BA44002CFEA]
GO

USE [DBMBCORP]
GO

/****** Object:  Table [dbo].[Carteira]    Script Date: 09/09/2014 12:12:14 ******/

GO

/****** Object:  Table [dbo].[Carteira]    Script Date: 09/09/2014 12:11:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Carteira](
	[ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [DBMBCORP]
GO


USE [DBMBCORP]
GO


/****** Object:  Table [dbo].[Operacao]    Script Date: 09/09/2014 12:12:14 ******/
GO

/****** Object:  Table [dbo].[Operacao]    Script Date: 09/09/2014 12:12:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Operacao](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VALOR] [float] NULL,
	[DATA] [datetime] NULL,
	[QUANTIDADE] [int] NULL,
	[TIPO] [nvarchar](255) NULL,
	[CODIGO] [nvarchar](255) NULL,
	[ID_CARTEIRA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Operacao]  WITH CHECK ADD  CONSTRAINT [FKB881C31C848973CB] FOREIGN KEY([CODIGO])
REFERENCES [dbo].[ACAO] ([CODIGO])
GO

ALTER TABLE [dbo].[Operacao] CHECK CONSTRAINT [FKB881C31C848973CB]
GO

ALTER TABLE [dbo].[Operacao]  WITH CHECK ADD  CONSTRAINT [FKB881C31CC5B6B876] FOREIGN KEY([ID_CARTEIRA])
REFERENCES [dbo].[Carteira] ([ID])
GO

ALTER TABLE [dbo].[Operacao] CHECK CONSTRAINT [FKB881C31CC5B6B876]
GO

INSERT INTO Empresa values('123','PETROBRAS')
INSERT INTO Empresa values('456','VALE')


