//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestesIntegrados.ServicoDeDadosJBS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoDeDadosJBS.IServicoDeDadosJBS")]
    public interface IServicoDeDadosJBS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoDeDadosJBS/RetornarListaDeVeiculos", ReplyAction="http://tempuri.org/IServicoDeDadosJBS/RetornarListaDeVeiculosResponse")]
        JBSDAL.VeiculoDTO[] RetornarListaDeVeiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoDeDadosJBS/RetornarListaDeVeiculos", ReplyAction="http://tempuri.org/IServicoDeDadosJBS/RetornarListaDeVeiculosResponse")]
        System.Threading.Tasks.Task<JBSDAL.VeiculoDTO[]> RetornarListaDeVeiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoDeDadosJBS/InserirVeiculo", ReplyAction="http://tempuri.org/IServicoDeDadosJBS/InserirVeiculoResponse")]
        bool InserirVeiculo(JBSDAL.VeiculoDTO veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoDeDadosJBS/InserirVeiculo", ReplyAction="http://tempuri.org/IServicoDeDadosJBS/InserirVeiculoResponse")]
        System.Threading.Tasks.Task<bool> InserirVeiculoAsync(JBSDAL.VeiculoDTO veiculo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoDeDadosJBSChannel : ServicoDeDadosJBS.IServicoDeDadosJBS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeDadosJBSClient : System.ServiceModel.ClientBase<ServicoDeDadosJBS.IServicoDeDadosJBS>, ServicoDeDadosJBS.IServicoDeDadosJBS {
        
        public ServicoDeDadosJBSClient() {
        }
        
        public ServicoDeDadosJBSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeDadosJBSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeDadosJBSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeDadosJBSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JBSDAL.VeiculoDTO[] RetornarListaDeVeiculos() {
            return base.Channel.RetornarListaDeVeiculos();
        }
        
        public System.Threading.Tasks.Task<JBSDAL.VeiculoDTO[]> RetornarListaDeVeiculosAsync() {
            return base.Channel.RetornarListaDeVeiculosAsync();
        }
        
        public bool InserirVeiculo(JBSDAL.VeiculoDTO veiculo) {
            return base.Channel.InserirVeiculo(veiculo);
        }
        
        public System.Threading.Tasks.Task<bool> InserirVeiculoAsync(JBSDAL.VeiculoDTO veiculo) {
            return base.Channel.InserirVeiculoAsync(veiculo);
        }
    }
}
