//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorJBSSemParar.ServicoDeDados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Veiculo", Namespace="http://schemas.datacontract.org/2004/07/DALVeiculo")]
    [System.SerializableAttribute()]
    public partial class Veiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoDeDados.IDadosVeiculo")]
    public interface IDadosVeiculo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDadosVeiculo/retornarVeiculos", ReplyAction="http://tempuri.org/IDadosVeiculo/retornarVeiculosResponse")]
        IntegradorJBSSemParar.ServicoDeDados.Veiculo[] retornarVeiculos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDadosVeiculo/retornarVeiculos", ReplyAction="http://tempuri.org/IDadosVeiculo/retornarVeiculosResponse")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoDeDados.Veiculo[]> retornarVeiculosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDadosVeiculo/Correr", ReplyAction="http://tempuri.org/IDadosVeiculo/CorrerResponse")]
        void Correr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDadosVeiculo/Correr", ReplyAction="http://tempuri.org/IDadosVeiculo/CorrerResponse")]
        System.Threading.Tasks.Task CorrerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDadosVeiculo/inserirVeiculo", ReplyAction="http://tempuri.org/IDadosVeiculo/inserirVeiculoResponse")]
        bool inserirVeiculo(IntegradorJBSSemParar.ServicoDeDados.Veiculo veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDadosVeiculo/inserirVeiculo", ReplyAction="http://tempuri.org/IDadosVeiculo/inserirVeiculoResponse")]
        System.Threading.Tasks.Task<bool> inserirVeiculoAsync(IntegradorJBSSemParar.ServicoDeDados.Veiculo veiculo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDadosVeiculoChannel : IntegradorJBSSemParar.ServicoDeDados.IDadosVeiculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DadosVeiculoClient : System.ServiceModel.ClientBase<IntegradorJBSSemParar.ServicoDeDados.IDadosVeiculo>, IntegradorJBSSemParar.ServicoDeDados.IDadosVeiculo {
        
        public DadosVeiculoClient() {
        }
        
        public DadosVeiculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DadosVeiculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DadosVeiculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DadosVeiculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntegradorJBSSemParar.ServicoDeDados.Veiculo[] retornarVeiculos() {
            return base.Channel.retornarVeiculos();
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoDeDados.Veiculo[]> retornarVeiculosAsync() {
            return base.Channel.retornarVeiculosAsync();
        }
        
        public void Correr() {
            base.Channel.Correr();
        }
        
        public System.Threading.Tasks.Task CorrerAsync() {
            return base.Channel.CorrerAsync();
        }
        
        public bool inserirVeiculo(IntegradorJBSSemParar.ServicoDeDados.Veiculo veiculo) {
            return base.Channel.inserirVeiculo(veiculo);
        }
        
        public System.Threading.Tasks.Task<bool> inserirVeiculoAsync(IntegradorJBSSemParar.ServicoDeDados.Veiculo veiculo) {
            return base.Channel.inserirVeiculoAsync(veiculo);
        }
    }
}
