//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoParaTestes.ServicoIntegradorSistemaPedagio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoIntegradorSistemaPedagio.IIntegradorSistemaPedagio")]
    public interface IIntegradorSistemaPedagio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSistemaPedagio/EnviarRequisicaoSOAP", ReplyAction="http://tempuri.org/IIntegradorSistemaPedagio/EnviarRequisicaoSOAPResponse")]
        string EnviarRequisicaoSOAP(string mensagemSOAP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegradorSistemaPedagio/EnviarRequisicaoSOAP", ReplyAction="http://tempuri.org/IIntegradorSistemaPedagio/EnviarRequisicaoSOAPResponse")]
        System.Threading.Tasks.Task<string> EnviarRequisicaoSOAPAsync(string mensagemSOAP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegradorSistemaPedagioChannel : AplicacaoParaTestes.ServicoIntegradorSistemaPedagio.IIntegradorSistemaPedagio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegradorSistemaPedagioClient : System.ServiceModel.ClientBase<AplicacaoParaTestes.ServicoIntegradorSistemaPedagio.IIntegradorSistemaPedagio>, AplicacaoParaTestes.ServicoIntegradorSistemaPedagio.IIntegradorSistemaPedagio {
        
        public IntegradorSistemaPedagioClient() {
        }
        
        public IntegradorSistemaPedagioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegradorSistemaPedagioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradorSistemaPedagioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegradorSistemaPedagioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EnviarRequisicaoSOAP(string mensagemSOAP) {
            return base.Channel.EnviarRequisicaoSOAP(mensagemSOAP);
        }
        
        public System.Threading.Tasks.Task<string> EnviarRequisicaoSOAPAsync(string mensagemSOAP) {
            return base.Channel.EnviarRequisicaoSOAPAsync(mensagemSOAP);
        }
    }
}
