// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace MBCorpHealthTestTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinList uIAlternadordeTarefasList = this.UIItemWindow.UIAlternadordeTarefasList;
            WinClient uIEspaçodetrabalhoClient = this.UIDomainDrivenDesigncoWindow.UIItemWindow.UIEspaçodetrabalhoClient;
            WinClient uIApresentaçãodeslidesClient = this.UIApresentaçãodeslidesWindow.UIApresentaçãodeslidesClient;
            WinButton uIDescartarButton = this.UIMicrosoftPowerPointWindow.UIDescartarWindow.UIDescartarButton;
            #endregion

            // Click 'Alternador de Tarefas' list box
            Mouse.Click(uIAlternadordeTarefasList, new Point(315, 253));

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(632, 527));

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(649, 606));

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(1517, 464));

            // Type 'asdff' in 'Espaço de trabalho' client
            Keyboard.SendKeys(uIEspaçodetrabalhoClient, this.RecordedMethod1Params.UIEspaçodetrabalhoClientSendKeys, ModifierKeys.None);

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(1341, 594));

            // Type '{Escape}' in 'Espaço de trabalho' client
            Keyboard.SendKeys(uIEspaçodetrabalhoClient, this.RecordedMethod1Params.UIEspaçodetrabalhoClientSendKeys1, ModifierKeys.None);

            // Click 'Apresentação de slides do PowerPoint - [Domain Dri...' client
            Mouse.Click(uIApresentaçãodeslidesClient, new Point(973, 875));

            // Type '{Escape}' in 'Apresentação de slides do PowerPoint - [Domain Dri...' client
            Keyboard.SendKeys(uIApresentaçãodeslidesClient, this.RecordedMethod1Params.UIApresentaçãodeslidesClientSendKeys, ModifierKeys.None);

            // Click 'Descar&tar' button
            Mouse.Click(uIDescartarButton, new Point(77, 20));

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(787, 494));

            // Type 'sadf' in 'Espaço de trabalho' client
            Keyboard.SendKeys(uIEspaçodetrabalhoClient, this.RecordedMethod1Params.UIEspaçodetrabalhoClientSendKeys2, ModifierKeys.None);

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(749, 228));

            // Type 's' in 'Espaço de trabalho' client
            Keyboard.SendKeys(uIEspaçodetrabalhoClient, this.RecordedMethod1Params.UIEspaçodetrabalhoClientSendKeys3, ModifierKeys.None);

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(1246, 563));

            // Type 'sdfasdf' in 'Espaço de trabalho' client
            Keyboard.SendKeys(uIEspaçodetrabalhoClient, this.RecordedMethod1Params.UIEspaçodetrabalhoClientSendKeys4, ModifierKeys.None);

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(139, 427));

            // Click 'Espaço de trabalho' client
            Mouse.Click(uIEspaçodetrabalhoClient, new Point(1045, 544));

            // Type '.{Space}teste' in 'Espaço de trabalho' client
            Keyboard.SendKeys(uIEspaçodetrabalhoClient, this.RecordedMethod1Params.UIEspaçodetrabalhoClientSendKeys5, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIDomainDrivenDesigncoWindow UIDomainDrivenDesigncoWindow
        {
            get
            {
                if ((this.mUIDomainDrivenDesigncoWindow == null))
                {
                    this.mUIDomainDrivenDesigncoWindow = new UIDomainDrivenDesigncoWindow();
                }
                return this.mUIDomainDrivenDesigncoWindow;
            }
        }
        
        public UIApresentaçãodeslidesWindow UIApresentaçãodeslidesWindow
        {
            get
            {
                if ((this.mUIApresentaçãodeslidesWindow == null))
                {
                    this.mUIApresentaçãodeslidesWindow = new UIApresentaçãodeslidesWindow();
                }
                return this.mUIApresentaçãodeslidesWindow;
            }
        }
        
        public UIMicrosoftPowerPointWindow UIMicrosoftPowerPointWindow
        {
            get
            {
                if ((this.mUIMicrosoftPowerPointWindow == null))
                {
                    this.mUIMicrosoftPowerPointWindow = new UIMicrosoftPowerPointWindow();
                }
                return this.mUIMicrosoftPowerPointWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIItemWindow mUIItemWindow;
        
        private UIDomainDrivenDesigncoWindow mUIDomainDrivenDesigncoWindow;
        
        private UIApresentaçãodeslidesWindow mUIApresentaçãodeslidesWindow;
        
        private UIMicrosoftPowerPointWindow mUIMicrosoftPowerPointWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'asdff' in 'Espaço de trabalho' client
        /// </summary>
        public string UIEspaçodetrabalhoClientSendKeys = "asdff";
        
        /// <summary>
        /// Type '{Escape}' in 'Espaço de trabalho' client
        /// </summary>
        public string UIEspaçodetrabalhoClientSendKeys1 = "{Escape}";
        
        /// <summary>
        /// Type '{Escape}' in 'Apresentação de slides do PowerPoint - [Domain Dri...' client
        /// </summary>
        public string UIApresentaçãodeslidesClientSendKeys = "{Escape}";
        
        /// <summary>
        /// Type 'sadf' in 'Espaço de trabalho' client
        /// </summary>
        public string UIEspaçodetrabalhoClientSendKeys2 = "sadf";
        
        /// <summary>
        /// Type 's' in 'Espaço de trabalho' client
        /// </summary>
        public string UIEspaçodetrabalhoClientSendKeys3 = "s";
        
        /// <summary>
        /// Type 'sdfasdf' in 'Espaço de trabalho' client
        /// </summary>
        public string UIEspaçodetrabalhoClientSendKeys4 = "sdfasdf";
        
        /// <summary>
        /// Type '.{Space}teste' in 'Espaço de trabalho' client
        /// </summary>
        public string UIEspaçodetrabalhoClientSendKeys5 = ".{Space}teste";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public WinList UIAlternadordeTarefasList
        {
            get
            {
                if ((this.mUIAlternadordeTarefasList == null))
                {
                    this.mUIAlternadordeTarefasList = new WinList(this);
                    #region Search Criteria
                    this.mUIAlternadordeTarefasList.SearchProperties[WinList.PropertyNames.Name] = "Alternador de Tarefas";
                    #endregion
                }
                return this.mUIAlternadordeTarefasList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIAlternadordeTarefasList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIDomainDrivenDesigncoWindow : WinWindow
    {
        
        public UIDomainDrivenDesigncoWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Domain Driven Design com C# - Aula 9.pptx - PowerPoint";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "PPTFrameClass";
            this.WindowTitles.Add("Domain Driven Design com C# - Aula 9.pptx - PowerPoint");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1071";
            this.WindowTitles.Add("Domain Driven Design com C# - Aula 9.pptx - PowerPoint");
            #endregion
        }
        
        #region Properties
        public WinClient UIEspaçodetrabalhoClient
        {
            get
            {
                if ((this.mUIEspaçodetrabalhoClient == null))
                {
                    this.mUIEspaçodetrabalhoClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIEspaçodetrabalhoClient.WindowTitles.Add("Domain Driven Design com C# - Aula 9.pptx - PowerPoint");
                    #endregion
                }
                return this.mUIEspaçodetrabalhoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIEspaçodetrabalhoClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIApresentaçãodeslidesWindow : WinWindow
    {
        
        public UIApresentaçãodeslidesWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Apresentação de slides do PowerPoint - [Domain Driven Design com C# - Aula 9.pptx" +
                "]";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "screenClass";
            this.WindowTitles.Add("Apresentação de slides do PowerPoint - [Domain Driven Design com C# - Aula 9.pptx" +
                    "]");
            #endregion
        }
        
        #region Properties
        public WinClient UIApresentaçãodeslidesClient
        {
            get
            {
                if ((this.mUIApresentaçãodeslidesClient == null))
                {
                    this.mUIApresentaçãodeslidesClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIApresentaçãodeslidesClient.SearchProperties[WinControl.PropertyNames.Name] = "Apresentação de slides do PowerPoint - [Domain Driven Design com C# - Aula 9.pptx" +
                        "]";
                    this.mUIApresentaçãodeslidesClient.WindowTitles.Add("Apresentação de slides do PowerPoint - [Domain Driven Design com C# - Aula 9.pptx" +
                            "]");
                    #endregion
                }
                return this.mUIApresentaçãodeslidesClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIApresentaçãodeslidesClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIMicrosoftPowerPointWindow : WinWindow
    {
        
        public UIMicrosoftPowerPointWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Microsoft PowerPoint";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Microsoft PowerPoint");
            #endregion
        }
        
        #region Properties
        public UIDescartarWindow UIDescartarWindow
        {
            get
            {
                if ((this.mUIDescartarWindow == null))
                {
                    this.mUIDescartarWindow = new UIDescartarWindow(this);
                }
                return this.mUIDescartarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDescartarWindow mUIDescartarWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIDescartarWindow : WinWindow
    {
        
        public UIDescartarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "102";
            this.WindowTitles.Add("Microsoft PowerPoint");
            #endregion
        }
        
        #region Properties
        public WinButton UIDescartarButton
        {
            get
            {
                if ((this.mUIDescartarButton == null))
                {
                    this.mUIDescartarButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDescartarButton.SearchProperties[WinButton.PropertyNames.Name] = "Descartar";
                    this.mUIDescartarButton.WindowTitles.Add("Microsoft PowerPoint");
                    #endregion
                }
                return this.mUIDescartarButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDescartarButton;
        #endregion
    }
}
