//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorJBSSemParar.ServicoViaFacil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cgmp.com", ConfigurationName="ServicoViaFacil.ValePedagio")]
    public interface ValePedagio {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cadastrarRotaTemporariaReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.InfoRota cadastrarRotaTemporaria(int[] pracas, string nome, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cadastrarRotaTemporariaReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.InfoRota> cadastrarRotaTemporariaAsync(int[] pracas, string nome, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="listarRotasReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.InfoRota[] listarRotas(long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="listarRotasReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.InfoRota[]> listarRotasAsync(long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterCustoRotaReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.CustoRota obterCustoRota(string nomeRota, string placa, int nEixos, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime inicioVigencia, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fimVigencia, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterCustoRotaReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.CustoRota> obterCustoRotaAsync(string nomeRota, string placa, int nEixos, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime inicioVigencia, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fimVigencia, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterStatusVeiculoReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.Veiculo[] obterStatusVeiculo(string placa, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterStatusVeiculoReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Veiculo[]> obterStatusVeiculoAsync(string placa, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="comprarViagemReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.Viagem comprarViagem(string rota, string placa, int nEixos, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime inicioVigencia, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fimVigencia, string itemFin1, string itemFin2, string itemFin3, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="comprarViagemReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Viagem> comprarViagemAsync(string rota, string placa, int nEixos, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime inicioVigencia, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fimVigencia, string itemFin1, string itemFin2, string itemFin3, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterReciboViagemReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.Recibo obterReciboViagem(long viagem, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterReciboViagemReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Recibo> obterReciboViagemAsync(long viagem, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelarViagemReturn")]
        int cancelarViagem(long viagem, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelarViagemReturn")]
        System.Threading.Tasks.Task<int> cancelarViagemAsync(long viagem, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consultarStatusViagemReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.StatusViagem[] consultarStatusViagem(string rota, string idSolicit, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consultarStatusViagemReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.StatusViagem[]> consultarStatusViagemAsync(string rota, string idSolicit, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reemitirViagemReturn")]
        int reemitirViagem(long viagem, string placa, string pracas, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="reemitirViagemReturn")]
        System.Threading.Tasks.Task<int> reemitirViagemAsync(long viagem, string placa, string pracas, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="listaPracasPedagioReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.InfoPracaPedagio[] listaPracasPedagio(long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="listaPracasPedagioReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.InfoPracaPedagio[]> listaPracasPedagioAsync(long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="autenticarUsuarioReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.Identificador autenticarUsuario(string cnpj, string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="autenticarUsuarioReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Identificador> autenticarUsuarioAsync(string cnpj, string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="comprarViagemComObservacoesReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.Viagem comprarViagemComObservacoes(string rota, string placa, int nEixos, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime inicioVigencia, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fimVigencia, IntegradorJBSSemParar.ServicoViaFacil.Observacoes observacoes, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="comprarViagemComObservacoesReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Viagem> comprarViagemComObservacoesAsync(string rota, string placa, int nEixos, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime inicioVigencia, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fimVigencia, IntegradorJBSSemParar.ServicoViaFacil.Observacoes observacoes, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterExtratoCreditosReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.ExtratoCredito[] obterExtratoCreditos(System.DateTime inicio, System.DateTime fim, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterExtratoCreditosReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.ExtratoCredito[]> obterExtratoCreditosAsync(System.DateTime inicio, System.DateTime fim, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterValoresPracasRotaReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.ValoresPracasRota obterValoresPracasRota(IntegradorJBSSemParar.ServicoViaFacil.Rota rota, IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterValoresPracasRotaReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.ValoresPracasRota> obterValoresPracasRotaAsync(IntegradorJBSSemParar.ServicoViaFacil.Rota rota, IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtratoCredito))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfoPracaPedagio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StatusViagem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Veiculo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PracaRota))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterValoresPracasReturn")]
        IntegradorJBSSemParar.ServicoViaFacil.ValoresPracas obterValoresPracas(IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obterValoresPracasReturn")]
        System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.ValoresPracas> obterValoresPracasAsync(IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class InfoRota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nomeField;
        
        private PracaRota[] pracasField;
        
        private int statusField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PracaRota[] pracas {
            get {
                return this.pracasField;
            }
            set {
                this.pracasField = value;
                this.RaisePropertyChanged("pracas");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class PracaRota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomeConcessionariaField;
        
        private string nomePracaField;
        
        private string nomeRodoviaField;
        
        private string placaField;
        
        private string tagField;
        
        private System.Nullable<decimal> tarifaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeConcessionaria {
            get {
                return this.nomeConcessionariaField;
            }
            set {
                this.nomeConcessionariaField = value;
                this.RaisePropertyChanged("nomeConcessionaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomePraca {
            get {
                return this.nomePracaField;
            }
            set {
                this.nomePracaField = value;
                this.RaisePropertyChanged("nomePraca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeRodovia {
            get {
                return this.nomeRodoviaField;
            }
            set {
                this.nomeRodoviaField = value;
                this.RaisePropertyChanged("nomeRodovia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class ValoresPracas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CategoriaVeiculo categoriaField;
        
        private System.Nullable<System.DateTime> dataConsultaField;
        
        private PracaRota[] pracaRotaField;
        
        private int statusField;
        
        private TipoVeiculo tipoVeiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CategoriaVeiculo categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataConsulta {
            get {
                return this.dataConsultaField;
            }
            set {
                this.dataConsultaField = value;
                this.RaisePropertyChanged("dataConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PracaRota[] pracaRota {
            get {
                return this.pracaRotaField;
            }
            set {
                this.pracaRotaField = value;
                this.RaisePropertyChanged("pracaRota");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TipoVeiculo tipoVeiculo {
            get {
                return this.tipoVeiculoField;
            }
            set {
                this.tipoVeiculoField = value;
                this.RaisePropertyChanged("tipoVeiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class CategoriaVeiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descricaoField;
        
        private int eixosField;
        
        private int statusField;
        
        private int tipoRodagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        public int eixos {
            get {
                return this.eixosField;
            }
            set {
                this.eixosField = value;
                this.RaisePropertyChanged("eixos");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public int tipoRodagem {
            get {
                return this.tipoRodagemField;
            }
            set {
                this.tipoRodagemField = value;
                this.RaisePropertyChanged("tipoRodagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class TipoVeiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoField;
        
        private string descricaoField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class ValoresPracasRota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CategoriaVeiculo categoriaField;
        
        private System.Nullable<System.DateTime> dataConsultaField;
        
        private Rota rotaField;
        
        private int statusField;
        
        private TipoVeiculo tipoVeiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CategoriaVeiculo categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataConsulta {
            get {
                return this.dataConsultaField;
            }
            set {
                this.dataConsultaField = value;
                this.RaisePropertyChanged("dataConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Rota rota {
            get {
                return this.rotaField;
            }
            set {
                this.rotaField = value;
                this.RaisePropertyChanged("rota");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TipoVeiculo tipoVeiculo {
            get {
                return this.tipoVeiculoField;
            }
            set {
                this.tipoVeiculoField = value;
                this.RaisePropertyChanged("tipoVeiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class Rota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codigoField;
        
        private string nomeField;
        
        private PracaRota[] pracasField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PracaRota[] pracas {
            get {
                return this.pracasField;
            }
            set {
                this.pracasField = value;
                this.RaisePropertyChanged("pracas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class ExtratoCredito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acaoField;
        
        private string cnpjCpfTranspField;
        
        private System.Nullable<System.DateTime> dataCompraField;
        
        private System.Nullable<System.DateTime> dataFaturaField;
        
        private System.Nullable<System.DateTime> dataFimVigenciaField;
        
        private System.Nullable<System.DateTime> dataInicioVigenciaField;
        
        private System.Nullable<System.DateTime> dataOperacaoField;
        
        private System.Nullable<System.DateTime> dataPassagemField;
        
        private string descricaoField;
        
        private System.Nullable<int> faturaField;
        
        private string itemFinanceiro1Field;
        
        private string itemFinanceiro2Field;
        
        private string itemFinanceiro3Field;
        
        private string nomeConcessionariaField;
        
        private string nomePracaField;
        
        private string nomeRodoviaField;
        
        private string nomeRotaField;
        
        private string nomeTranspField;
        
        private long numeroField;
        
        private long numeroViagemField;
        
        private string placaField;
        
        private System.Nullable<decimal> saldoDiaField;
        
        private int statusField;
        
        private string tagField;
        
        private int tipoVPField;
        
        private System.Nullable<decimal> valorOperacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acao {
            get {
                return this.acaoField;
            }
            set {
                this.acaoField = value;
                this.RaisePropertyChanged("acao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpjCpfTransp {
            get {
                return this.cnpjCpfTranspField;
            }
            set {
                this.cnpjCpfTranspField = value;
                this.RaisePropertyChanged("cnpjCpfTransp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataCompra {
            get {
                return this.dataCompraField;
            }
            set {
                this.dataCompraField = value;
                this.RaisePropertyChanged("dataCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFatura {
            get {
                return this.dataFaturaField;
            }
            set {
                this.dataFaturaField = value;
                this.RaisePropertyChanged("dataFatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFimVigencia {
            get {
                return this.dataFimVigenciaField;
            }
            set {
                this.dataFimVigenciaField = value;
                this.RaisePropertyChanged("dataFimVigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataInicioVigencia {
            get {
                return this.dataInicioVigenciaField;
            }
            set {
                this.dataInicioVigenciaField = value;
                this.RaisePropertyChanged("dataInicioVigencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataOperacao {
            get {
                return this.dataOperacaoField;
            }
            set {
                this.dataOperacaoField = value;
                this.RaisePropertyChanged("dataOperacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataPassagem {
            get {
                return this.dataPassagemField;
            }
            set {
                this.dataPassagemField = value;
                this.RaisePropertyChanged("dataPassagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> fatura {
            get {
                return this.faturaField;
            }
            set {
                this.faturaField = value;
                this.RaisePropertyChanged("fatura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string itemFinanceiro1 {
            get {
                return this.itemFinanceiro1Field;
            }
            set {
                this.itemFinanceiro1Field = value;
                this.RaisePropertyChanged("itemFinanceiro1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string itemFinanceiro2 {
            get {
                return this.itemFinanceiro2Field;
            }
            set {
                this.itemFinanceiro2Field = value;
                this.RaisePropertyChanged("itemFinanceiro2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string itemFinanceiro3 {
            get {
                return this.itemFinanceiro3Field;
            }
            set {
                this.itemFinanceiro3Field = value;
                this.RaisePropertyChanged("itemFinanceiro3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeConcessionaria {
            get {
                return this.nomeConcessionariaField;
            }
            set {
                this.nomeConcessionariaField = value;
                this.RaisePropertyChanged("nomeConcessionaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomePraca {
            get {
                return this.nomePracaField;
            }
            set {
                this.nomePracaField = value;
                this.RaisePropertyChanged("nomePraca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeRodovia {
            get {
                return this.nomeRodoviaField;
            }
            set {
                this.nomeRodoviaField = value;
                this.RaisePropertyChanged("nomeRodovia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeRota {
            get {
                return this.nomeRotaField;
            }
            set {
                this.nomeRotaField = value;
                this.RaisePropertyChanged("nomeRota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeTransp {
            get {
                return this.nomeTranspField;
            }
            set {
                this.nomeTranspField = value;
                this.RaisePropertyChanged("nomeTransp");
            }
        }
        
        /// <remarks/>
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        public long numeroViagem {
            get {
                return this.numeroViagemField;
            }
            set {
                this.numeroViagemField = value;
                this.RaisePropertyChanged("numeroViagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> saldoDia {
            get {
                return this.saldoDiaField;
            }
            set {
                this.saldoDiaField = value;
                this.RaisePropertyChanged("saldoDia");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        /// <remarks/>
        public int tipoVP {
            get {
                return this.tipoVPField;
            }
            set {
                this.tipoVPField = value;
                this.RaisePropertyChanged("tipoVP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valorOperacao {
            get {
                return this.valorOperacaoField;
            }
            set {
                this.valorOperacaoField = value;
                this.RaisePropertyChanged("valorOperacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class Observacoes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string observacao1Field;
        
        private string observacao2Field;
        
        private string observacao3Field;
        
        private string observacao4Field;
        
        private string observacao5Field;
        
        private string observacao6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao1 {
            get {
                return this.observacao1Field;
            }
            set {
                this.observacao1Field = value;
                this.RaisePropertyChanged("observacao1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao2 {
            get {
                return this.observacao2Field;
            }
            set {
                this.observacao2Field = value;
                this.RaisePropertyChanged("observacao2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao3 {
            get {
                return this.observacao3Field;
            }
            set {
                this.observacao3Field = value;
                this.RaisePropertyChanged("observacao3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao4 {
            get {
                return this.observacao4Field;
            }
            set {
                this.observacao4Field = value;
                this.RaisePropertyChanged("observacao4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao5 {
            get {
                return this.observacao5Field;
            }
            set {
                this.observacao5Field = value;
                this.RaisePropertyChanged("observacao5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao6 {
            get {
                return this.observacao6Field;
            }
            set {
                this.observacao6Field = value;
                this.RaisePropertyChanged("observacao6");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class Identificador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long sessaoField;
        
        private int statusField;
        
        /// <remarks/>
        public long sessao {
            get {
                return this.sessaoField;
            }
            set {
                this.sessaoField = value;
                this.RaisePropertyChanged("sessao");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class InfoPracaPedagio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string concessionariaField;
        
        private long idField;
        
        private float kmField;
        
        private string pracaField;
        
        private string rodoviaField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string concessionaria {
            get {
                return this.concessionariaField;
            }
            set {
                this.concessionariaField = value;
                this.RaisePropertyChanged("concessionaria");
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public float km {
            get {
                return this.kmField;
            }
            set {
                this.kmField = value;
                this.RaisePropertyChanged("km");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string praca {
            get {
                return this.pracaField;
            }
            set {
                this.pracaField = value;
                this.RaisePropertyChanged("praca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rodovia {
            get {
                return this.rodoviaField;
            }
            set {
                this.rodoviaField = value;
                this.RaisePropertyChanged("rodovia");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class StatusViagem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroField;
        
        private int statusField;
        
        private int statusViagemField;
        
        /// <remarks/>
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public int statusViagem {
            get {
                return this.statusViagemField;
            }
            set {
                this.statusViagemField = value;
                this.RaisePropertyChanged("statusViagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class Recibo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string catVeiculoField;
        
        private string cnpjEmissorField;
        
        private string cnpjTranspField;
        
        private System.Nullable<System.DateTime> dataCompraField;
        
        private System.Nullable<System.DateTime> dataExpField;
        
        private System.Nullable<System.DateTime> dataViagemField;
        
        private string logoField;
        
        private string nomeEmissorField;
        
        private string nomeRotaField;
        
        private string nomeTranspField;
        
        private string obsField;
        
        private PracaRota[] pracasField;
        
        private int statusField;
        
        private string tipoField;
        
        private System.Nullable<decimal> totalField;
        
        private long viagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string catVeiculo {
            get {
                return this.catVeiculoField;
            }
            set {
                this.catVeiculoField = value;
                this.RaisePropertyChanged("catVeiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpjEmissor {
            get {
                return this.cnpjEmissorField;
            }
            set {
                this.cnpjEmissorField = value;
                this.RaisePropertyChanged("cnpjEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpjTransp {
            get {
                return this.cnpjTranspField;
            }
            set {
                this.cnpjTranspField = value;
                this.RaisePropertyChanged("cnpjTransp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataCompra {
            get {
                return this.dataCompraField;
            }
            set {
                this.dataCompraField = value;
                this.RaisePropertyChanged("dataCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataExp {
            get {
                return this.dataExpField;
            }
            set {
                this.dataExpField = value;
                this.RaisePropertyChanged("dataExp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataViagem {
            get {
                return this.dataViagemField;
            }
            set {
                this.dataViagemField = value;
                this.RaisePropertyChanged("dataViagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
                this.RaisePropertyChanged("logo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeEmissor {
            get {
                return this.nomeEmissorField;
            }
            set {
                this.nomeEmissorField = value;
                this.RaisePropertyChanged("nomeEmissor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeRota {
            get {
                return this.nomeRotaField;
            }
            set {
                this.nomeRotaField = value;
                this.RaisePropertyChanged("nomeRota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeTransp {
            get {
                return this.nomeTranspField;
            }
            set {
                this.nomeTranspField = value;
                this.RaisePropertyChanged("nomeTransp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
                this.RaisePropertyChanged("obs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PracaRota[] pracas {
            get {
                return this.pracasField;
            }
            set {
                this.pracasField = value;
                this.RaisePropertyChanged("pracas");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        public long viagem {
            get {
                return this.viagemField;
            }
            set {
                this.viagemField = value;
                this.RaisePropertyChanged("viagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class Viagem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroField;
        
        private int statusField;
        
        /// <remarks/>
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class Veiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descricaoField;
        
        private int eixosField;
        
        private string placaField;
        
        private string proprietarioField;
        
        private int statusField;
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        public int eixos {
            get {
                return this.eixosField;
            }
            set {
                this.eixosField = value;
                this.RaisePropertyChanged("eixos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string proprietario {
            get {
                return this.proprietarioField;
            }
            set {
                this.proprietarioField = value;
                this.RaisePropertyChanged("proprietario");
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.dto.model.cgmp.com")]
    public partial class CustoRota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusField;
        
        private System.Nullable<decimal> valorField;
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValePedagioChannel : IntegradorJBSSemParar.ServicoViaFacil.ValePedagio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValePedagioClient : System.ServiceModel.ClientBase<IntegradorJBSSemParar.ServicoViaFacil.ValePedagio>, IntegradorJBSSemParar.ServicoViaFacil.ValePedagio {
        
        public ValePedagioClient() {
        }
        
        public ValePedagioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValePedagioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValePedagioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValePedagioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.InfoRota cadastrarRotaTemporaria(int[] pracas, string nome, long sessao) {
            return base.Channel.cadastrarRotaTemporaria(pracas, nome, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.InfoRota> cadastrarRotaTemporariaAsync(int[] pracas, string nome, long sessao) {
            return base.Channel.cadastrarRotaTemporariaAsync(pracas, nome, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.InfoRota[] listarRotas(long sessao) {
            return base.Channel.listarRotas(sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.InfoRota[]> listarRotasAsync(long sessao) {
            return base.Channel.listarRotasAsync(sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.CustoRota obterCustoRota(string nomeRota, string placa, int nEixos, System.DateTime inicioVigencia, System.DateTime fimVigencia, long sessao) {
            return base.Channel.obterCustoRota(nomeRota, placa, nEixos, inicioVigencia, fimVigencia, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.CustoRota> obterCustoRotaAsync(string nomeRota, string placa, int nEixos, System.DateTime inicioVigencia, System.DateTime fimVigencia, long sessao) {
            return base.Channel.obterCustoRotaAsync(nomeRota, placa, nEixos, inicioVigencia, fimVigencia, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.Veiculo[] obterStatusVeiculo(string placa, long sessao) {
            return base.Channel.obterStatusVeiculo(placa, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Veiculo[]> obterStatusVeiculoAsync(string placa, long sessao) {
            return base.Channel.obterStatusVeiculoAsync(placa, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.Viagem comprarViagem(string rota, string placa, int nEixos, System.DateTime inicioVigencia, System.DateTime fimVigencia, string itemFin1, string itemFin2, string itemFin3, long sessao) {
            return base.Channel.comprarViagem(rota, placa, nEixos, inicioVigencia, fimVigencia, itemFin1, itemFin2, itemFin3, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Viagem> comprarViagemAsync(string rota, string placa, int nEixos, System.DateTime inicioVigencia, System.DateTime fimVigencia, string itemFin1, string itemFin2, string itemFin3, long sessao) {
            return base.Channel.comprarViagemAsync(rota, placa, nEixos, inicioVigencia, fimVigencia, itemFin1, itemFin2, itemFin3, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.Recibo obterReciboViagem(long viagem, long sessao) {
            return base.Channel.obterReciboViagem(viagem, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Recibo> obterReciboViagemAsync(long viagem, long sessao) {
            return base.Channel.obterReciboViagemAsync(viagem, sessao);
        }
        
        public int cancelarViagem(long viagem, long sessao) {
            return base.Channel.cancelarViagem(viagem, sessao);
        }
        
        public System.Threading.Tasks.Task<int> cancelarViagemAsync(long viagem, long sessao) {
            return base.Channel.cancelarViagemAsync(viagem, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.StatusViagem[] consultarStatusViagem(string rota, string idSolicit, long sessao) {
            return base.Channel.consultarStatusViagem(rota, idSolicit, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.StatusViagem[]> consultarStatusViagemAsync(string rota, string idSolicit, long sessao) {
            return base.Channel.consultarStatusViagemAsync(rota, idSolicit, sessao);
        }
        
        public int reemitirViagem(long viagem, string placa, string pracas, long sessao) {
            return base.Channel.reemitirViagem(viagem, placa, pracas, sessao);
        }
        
        public System.Threading.Tasks.Task<int> reemitirViagemAsync(long viagem, string placa, string pracas, long sessao) {
            return base.Channel.reemitirViagemAsync(viagem, placa, pracas, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.InfoPracaPedagio[] listaPracasPedagio(long sessao) {
            return base.Channel.listaPracasPedagio(sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.InfoPracaPedagio[]> listaPracasPedagioAsync(long sessao) {
            return base.Channel.listaPracasPedagioAsync(sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.Identificador autenticarUsuario(string cnpj, string login, string senha) {
            return base.Channel.autenticarUsuario(cnpj, login, senha);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Identificador> autenticarUsuarioAsync(string cnpj, string login, string senha) {
            return base.Channel.autenticarUsuarioAsync(cnpj, login, senha);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.Viagem comprarViagemComObservacoes(string rota, string placa, int nEixos, System.DateTime inicioVigencia, System.DateTime fimVigencia, IntegradorJBSSemParar.ServicoViaFacil.Observacoes observacoes, long sessao) {
            return base.Channel.comprarViagemComObservacoes(rota, placa, nEixos, inicioVigencia, fimVigencia, observacoes, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.Viagem> comprarViagemComObservacoesAsync(string rota, string placa, int nEixos, System.DateTime inicioVigencia, System.DateTime fimVigencia, IntegradorJBSSemParar.ServicoViaFacil.Observacoes observacoes, long sessao) {
            return base.Channel.comprarViagemComObservacoesAsync(rota, placa, nEixos, inicioVigencia, fimVigencia, observacoes, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.ExtratoCredito[] obterExtratoCreditos(System.DateTime inicio, System.DateTime fim, long sessao) {
            return base.Channel.obterExtratoCreditos(inicio, fim, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.ExtratoCredito[]> obterExtratoCreditosAsync(System.DateTime inicio, System.DateTime fim, long sessao) {
            return base.Channel.obterExtratoCreditosAsync(inicio, fim, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.ValoresPracasRota obterValoresPracasRota(IntegradorJBSSemParar.ServicoViaFacil.Rota rota, IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao) {
            return base.Channel.obterValoresPracasRota(rota, categoria, tipoVeiculo, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.ValoresPracasRota> obterValoresPracasRotaAsync(IntegradorJBSSemParar.ServicoViaFacil.Rota rota, IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao) {
            return base.Channel.obterValoresPracasRotaAsync(rota, categoria, tipoVeiculo, sessao);
        }
        
        public IntegradorJBSSemParar.ServicoViaFacil.ValoresPracas obterValoresPracas(IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao) {
            return base.Channel.obterValoresPracas(categoria, tipoVeiculo, sessao);
        }
        
        public System.Threading.Tasks.Task<IntegradorJBSSemParar.ServicoViaFacil.ValoresPracas> obterValoresPracasAsync(IntegradorJBSSemParar.ServicoViaFacil.CategoriaVeiculo categoria, IntegradorJBSSemParar.ServicoViaFacil.TipoVeiculo tipoVeiculo, long sessao) {
            return base.Channel.obterValoresPracasAsync(categoria, tipoVeiculo, sessao);
        }
    }
}
