DROP TABLE TBVEICULO;
CREATE TABLE TBVEICULO
(
PLACA VARCHAR(7),
CATEGORIA INT
);

INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('FHZ9752',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('EDL4512',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('EDL4896',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('CLJ6910',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('EPO2327',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('DVS9096',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('BYD0254',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('BTR9286',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('CVP2607',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('BVQ5533',3);
INSERT INTO TBVEICULO(PLACA,CATEGORIA) VALUES ('BXI4763',3);

CREATE OR REPLACE PROCEDURE SP_RETORNARVEICULOS
(
VEICULOS OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN VEICULOS FOR SELECT PLACA,CATEGORIA FROM TBVEICULO;
END; 


CREATE OR REPLACE PROCEDURE SP_INSERIRVEICULO
(
PLACA IN VARCHAR,
CATEGORIA IN INT
)
IS
BEGIN
  INSERT INTO TBVEICULO VALUES(PLACA,CATEGORIA);
END; 



